version: '3.8'

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE_AUTH}
      POSTGRES_USER: ${DB_USERNAME_AUTH}
      POSTGRES_PASSWORD: ${DB_PASSWORD_AUTH}
    ports:
      - "${DB_PORT_AUTH}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
